### ISSUE TITLE
u-boot error

### ISSUE THREAD

**Issue by mihaelaapetroaie** [jumpnow/meta-odroid-c2#1]
Hello, 

I am getting the following error when trying to bitbake, was wondering if you know where it could come from:

`ERROR: No recipes available for:
  /storage/mika/odroid/poky/meta-odroid-c2/recipes-bsp/u-boot/u-boot_2017.09.bbappend
`

I am building the rocko branch.

Thank you,
Mihaela

**Comment by scottellis** [comment]
[rocko] or [sumo] branch ?


"Mihaela Apetroaie-Cristea" <notifications@github.com> said:

**Comment by mihaelaapetroaie** [comment]
Sorry, I was trying to build [rocko] branch, but some of my layers were pyro, should have checked that before. Thank you!
